### PR TITLE
Adding tet mesh option

### PR DESCRIPTION
**Pull request by Shimwell**
This PR adds the ability to generate tet meshes for the geometry

This is the first pass so it will need a bit more testing (I think the commands might have changed slightly) and I notice that the mesh sometimes makes a hex mesh instead of a tet mesh.

What do you think @AnderGray 

- [x] README.md has been updated with an example
- [x] tests have been added
- [x] functionality has been added to core.py

### CODE REVIEW

**Comment by Shimwell** [comment]
Looks like this is passing the tests so it is probably good enough to merge. Do let me know if anyone experiences any issues with this feature

**Comment by AnderGray** [comment]
All looks good and working on my side

**Comment by AnderGray** [comment]
I get the following error, but continues running :

```
[2021-08-24 10:45:20.953] [error] Unrecognized Identifier: 'geometric'

ERROR: <stdin>, line 21. Unrecognized Identifier: 'geometric'
[2021-08-24 10:45:20.954] [error] syntax error (<stdin>, line 22)

ERROR: <stdin>, line 21. syntax error (<stdin>, line 22)
Journaled Command: volume 3 size 0.5
```

**Comment by Shimwell** [comment]
I guess the python API has changed a bit, we could make a mesh manually and record the cubit commands to see how it works

**Comment by AnderGray** [comment]
I had the same error when running with journal/ gui. Could it be he syntax has changed with the cubit version?

**Comment by AnderGray** [comment]
It made it to the mesh export however

**Comment by Shimwell** [comment]
I think Cubit skips commands when they are incorrect. Which can give you the impression everything ran just fine.

**Pull request merged**
